import os
# os.mkdir(f"Projeto")
# print(f"Pasta criada!")
open("C:\Users\prog1\Documents\Isaac\Projeto/matematica.txt", "w").close()
open("C:\Users\prog1\Documents\Isaac\Projeto/portugues.txt", "w").close()
open("C:\Users\prog1\Documents\Isaac\Projeto/ciencias.txt", "w").close()
# # Projeto_listt = os.listdir("Projeto")
# # for item in Projeto_listt:
# #     print(item)
# os.rename("Projeto/portugues.txt", "Projeto/historia.txt")
# if os.path.exists("Projeto/matematica.txt"):
#     os.remove("Projeto/matematica.txt")
#     print(f"Arquivo apagado")
# else:
#     print(f"Arquivo não existente")
