Numero_Fl = float(input("numero quebrado:"))
Numero_IN = int(input("numero inteiro:"))
Texto_Str = str(input("Isso é um Str:"))
logico = bool(input("Você tem um celular?:"))
logico2 = bool(input("Você tem um celular?:"))

print("-----------------")
print(f"Float: {Numero_Fl}") 
print(f"Int: {Numero_IN}")
print(f"Str: {Texto_Str}")
print(f"Bool: {logico}")
print(f"Bool: {logico2}") 
print("-----------------")
